apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-demo
  namespace: secrets-demo
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-demo
  target:
    name: ext-postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: demo/aws-sm/ext-postgres-secret
      property: username
  - secretKey: password
    remoteRef:
      key: demo/aws-sm/ext-postgres-secret
      property: password
