apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: secrets-demo
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: NGINX_TLS_CRT
        value: /etc/nginx/ssl/tls.crt
      - name: NGINX_TLS_KEY
        value: /etc/nginx/ssl/tls.key
    volumeMounts:
     - name: nginx-certs
       mountPath: /etc/nginx/ssl
       readOnly: true
  volumes:
    - name: nginx-certs
      secret:
        secretName: demo-local-tls-secret

