# postgres-service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: secrets-demo
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
# mlflow pod
apiVersion: v1
kind: Pod
metadata:
  name: mlflow
  namespace: secrets-demo
spec:
  imagePullSecrets:
    - name: private-registry-secret
  containers:
  - name: mlflow
    image: registry.local/mlflow:v1
    env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: password
      - name: POSTGRES_DATABASE
        value: admin
    command: ["mlflow", "server", "--backend-store-uri", "postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DATABASE)"]
