---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ss-postgres-secret
  namespace: secrets-demo
spec:
  encryptedData:
    password: AgAWVLOrIQ+AwEU/sYxUBoE1Hmn4ECZgKeM0UYcRe7voj22osG/DIw11G0GRyzkNT/o2nYSEDq+ZP97IWGLE8YO5WvappapSlhJT/SynhKhuPSDANBWtZnTLqBHtIXSGyo4p51Oi3OUuidylzbq7hkIyqxS4rXJ5GBaSvKK1qjnhYKIPb3O2tc6MSHPfLl3vHaWL4lN8XCPxitI8kc+2qGVnszqwJlLjzdq0bds9Qkt4O5lUOJJSpkZRve2KO1WM/PfFJG+qzQ2m1u7SFNAMM3vh95l+3vLBv8mtNuFvSCOS4UcQGyrBJ0HuisjPe20W2YQWcsxZxX0VlfTWZm7EO94oFqSfNAgZ3Y2tlFRL8gsif+EL2fJ1GpqxvDSiYz6xEArIy9ZyeqLZLv9QfFffnrE9tox8rBo8gChmu32OWmXyFEAKBSCtavNaEEtdURov3NA9V2HP9F1R+XVKN/WBaq4T3RFQvkpASbKwaLI1QDl1ZPiOY89dbVPRChWzfqb0SNd/9YhRU3XLB/DxRAd2Ea057geLy0nH4xStQzRNd1hEA51KQ0GVn2O9ED2JFkQqly17lwBQAjykJKajgtJqq2PmgovR/dPdKwvbYk/yID85csyhsfUpa4QBlJCBaE6zkFrVBZv4DKd90X2wYBE9C3VsnwjGyrenNn+l9eAFTVvcFrRblF5bDRF61GN8JqF45HjLujslsreBm1qtSeMgzA==
    username: AgBccPMySp45n0jCgsnNUoU4DKFHKg4UcjfmXWLR//AZmBs6Ie1Hb5ujm6oajxvp0OA0TzHsTyPwjxH0Hz8eGmuP3k9YG6vAvtfKpwUWmeDaN98dhSxD485GjsBpGPsuVfPjqiQIyD0sUw9XNYbpoahAzPhf+E7QhmtHKdLHYZegg7/908tV/qPOazJfgIp8aPgIDnc/kwe+XCz0pdCCkmpm1ts9aIv0XdtLugzusxAfDWtfbvv5A1OC/pwSJ6ZB+TFyGIPQF1r8n7wCphthbhYfVqEKPwHbI/qEx97UDhRkmlizNxXPcOBIc2vM2efueMFbHPVZzF8cHe+xMTlBSxodYMAxLY7y/u0XOa03X6HE8Hft7y/jXVUCdWkQdDxvddWGXEYmWTLhc8pkcgVUh2/AWRplRfbPz3k0OkZ3jOoSV5CVC4f4oOcGPk3eWnHwUAEVzzuKg3Y59HrjjX6PCXxohMj3OCjG+gQ9zspUXNqiRigusiehpQqCZdAuBNSxIKHh6M0JYBYVGUV0HfeFfxvJRFUmQFUXq2i1dUDwvrDh05GS/K0LgCtsxlzp2lQlaDwY0vWAQcUlJuvyhXBWDstcWdKv4vIQxcGQcCDAp3EsIEA5Fxn2cZI38H4g6oDZivMAICaJ6BkoMnipI9ZnbA+Yvl+becrmBiDIioLgo/DfKQJb1fadzHaZBeYbttY3H7/bTHsIaA==
  template:
    metadata:
      creationTimestamp: null
      name: ss-postgres-secret
      namespace: secrets-demo
