apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-demo
  namespace: secrets-demo
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-secret
            key: AWS_SECRET_ACCESS_KEY
