apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-postgres-secret
  namespace: secrets-demo
spec:
  type: kv-v2
  mount: kv-secrets
  path: postgres/config

  destination:
    name: vault-postgres-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth
